In [1]:
#Importación de librerias
import numpy as np
import pandas as pd
import math
from matplotlib import pyplot as plt
import plotly.express as px

from Generico import Extraccion_caracteristicas, Graficos

from ipywidgets import interact, interact_manual

#Imprimir los graficos en el notebook
%matplotlib inline

In [2]:
#Variables generales
ruta_model = "../Model/"
ruta_df = "../Datasets/"

semilla = 111

---
### 2.1. Caracteristicas según el Dataset

* Interpolation Method

In [3]:
%%time
df_Interpolation_Method = pd.read_csv('{}data_Interpolation_Method_ThreeSigma.csv'.format(ruta_df))
df_Interpolation_Method

Wall time: 5.63 s

,CONS_NO,FLAG,2014/1/1,2014/1/10,2014/1/11,2014/1/12,2014/1/13,2014/1/14,2014/1/15,2014/1/16,...,2016/9/29,2016/9/3,2016/9/30,2016/9/4,2016/9/5,2016/9/6,2016/9/7,2016/9/8,2016/9/9,Three_Sigma_Rule
0,0387DD8A07E07FDA6271170F86AD9151,1,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,9.96,16.92,7.60,27.170209,18.05,26.47,18.75000,17.84,14.92,27.170209
1,01D6177B5D4FFE0CABA9EF17DAFC2B84,1,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.000000,0.00,0.00,0.00000,0.00,0.00,0.000000
2,4B75AC4F2D8434CFF62DB64D0BB43103,1,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.000000,0.00,0.00,0.00000,0.00,0.00,13.615858
3,B32AC8CC6D5D805AC053557AB05F5343,1,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,9.99,11.78,18.59,26.800000,18.57,14.59,12.82000,19.37,15.92,27.970284
4,EDFC78B07BA2908B3395C4EB2304665E,1,2.90,3.42,3.81,4.58,3.56,4.25,3.86,3.53,...,10.37,15.32,13.51,12.230000,14.68,16.35,18.14000,18.41,17.31,20.115057
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42367,F1472871E1AFF49D4289564B6377D76C,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,3.56,3.38,4.39,3.720000,3.77,3.96,3.64000,3.40,4.38,7.664272
42368,F3C8BBCD2DC26C1E0249DEEF6A4256B7,0,2.70,4.39,3.95,0.00,0.00,0.00,0.00,0.00,...,4.87,4.48,3.67,3.310000,4.58,3.33,3.19000,4.57,4.00,8.365176
42369,A9A0FE83467A680FBFB0DBFC910DF227,0,0.58,0.84,1.61,0.90,0.60,0.82,0.89,0.03,...,0.66,2.92,2.36,3.860000,4.28,3.37,5.08769,2.44,1.15,5.087690
42370,D9A6ADA018FA46A55D5438370456AA45,0,16.89,13.84,13.50,14.60,14.46,12.34,15.37,17.01,...,13.75,22.61,18.83,25.520000,18.11,19.31,17.48000,17.20,15.28,32.214247
42371,F3406636BAD1E6E0826E8EDDC9A1BF00,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,4.45,9.80,5.11,12.165835,12.04,9.90,8.23000,8.56,9.86,12.165835

In [4]:
df_IM_ = Extraccion_caracteristicas(df_Interpolation_Method, '2014/1/1', '2016/9/9')

In [5]:
%%time
df_IM_.Sum()
df_IM_.Mean()
df_IM_.Median()
df_IM_.Standard_Dev()
df_IM_.Variance()
df_IM_.Peak_to_Peak()
df_IM_.Kurtosis()
df_IM_.Quartile_1()
df_IM_.Quartile_3()
df_IM_.Norm()
df_IM_.IQR()
df_IM_.Percentile_15()
df_IM_.Percentile_65()
df_IM_.Percentile_85()
df_IM_.Median_Absolute_Deviation()
df_IM_.kstat()
df_IM_.KStatvar()

Wall time: 29.4 s

In [6]:
df_Interpolation_Method.fillna(0, inplace= True)
df_Interpolation_Method.sample(5)

,CONS_NO,FLAG,2014/1/1,2014/1/10,2014/1/11,2014/1/12,2014/1/13,2014/1/14,2014/1/15,2014/1/16,...,Quartile_1,Quartile_3,Norm,IQR,Percentile_15,Percentile_65,Percentile_85,Median_Absolute_Deviation,kstat,KStatvar
18007,938A25C48C9034E5F4D7CC5FA444CC54,0,6.260000,6.240000,6.72,6.03,8.23,8.37,11.730000,10.790000,...,5.3000,8.10,258.266771,2.8000,4.9100,7.1300,10.9720,1.205,12.112852,0.390313
16077,BA2F621FE0450777007F44B597D9B6B2,0,101.498569,101.498569,94.02,86.74,100.38,96.32,101.498569,99.750000,...,0.0000,64.83,1458.152759,64.8300,0.0000,39.1555,76.6045,0.000,1362.137870,1692.274869
9759,311029CFDD5C1575847C3A5B8669846B,0,14.470000,14.960000,12.86,16.34,18.81,19.84,20.100000,22.066165,...,12.4625,17.07,490.274304,4.6075,11.5485,16.1400,18.4620,2.310,10.923904,0.231238
22671,F7E78B0D03803C278B66369C49A8F632,0,0.000000,0.000000,0.00,10.58,12.50,15.18,0.000000,9.990000,...,7.6300,14.94,410.900234,7.3100,6.7500,12.3790,18.1405,3.120,29.248624,1.508925
11170,BDE9148B056C7FF12F25E082AAFA02EB,0,0.000000,0.000000,0.00,0.00,0.00,0.00,0.000000,0.000000,...,0.0000,0.00,0.000000,0.0000,0.0000,0.0000,0.0000,0.000,0.000000,0.000000

In [7]:
df_Interpolation_Method_grafico = Graficos(df_Interpolation_Method)

In [8]:
interact_manual(
    df_Interpolation_Method_grafico.BoxPlot
    , Caracteristica = df_Interpolation_Method.loc[:, 'Sum':]
    , limite = ['Ninguno', 'FLAG = 0', 'FLAG = 1', 'General']
)

interactive(children=(Dropdown(description='Caracteristica', options=('Sum', 'Mean', 'Median', 'Standard_Dev',…

* Regresión Lineal

In [9]:
%%time
df_Linear_Regression = pd.read_csv('{}data_Linear_Regression_ThreeSigma.csv'.format(ruta_df))
df_Linear_Regression

Wall time: 7.38 s

,CONS_NO,FLAG,0,1,2,3,4,5,6,7,...,1025,1026,1027,1028,1029,1030,1031,1032,1033,Three_Sigma_Rule
0,0387DD8A07E07FDA6271170F86AD9151,1,7.707457,2.665701,7.630088,9.913999,0.000000,11.317155,9.951795,7.715379,...,9.960000,16.920000,7.60000,27.059139,18.050000,26.470000,18.750000,17.840000,14.920000,27.059139
1,01D6177B5D4FFE0CABA9EF17DAFC2B84,1,7.164900,6.415890,7.128157,7.480464,13.251837,6.062481,6.670971,7.161427,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.251837
2,4B75AC4F2D8434CFF62DB64D0BB43103,1,2.999566,7.088437,9.476034,7.245008,19.489340,8.655320,5.556647,7.606887,...,4.119683,12.440778,19.48934,4.089500,7.441728,9.511913,10.946919,5.523557,8.044295,19.489340
3,B32AC8CC6D5D805AC053557AB05F5343,1,0.000000,4.325031,0.930686,3.998118,0.000000,10.950378,0.000000,3.717222,...,9.990000,11.780000,18.59000,26.800000,18.570000,14.590000,12.820000,19.370000,15.920000,30.312557
4,EDFC78B07BA2908B3395C4EB2304665E,1,2.900000,3.420000,3.810000,4.580000,3.560000,4.250000,3.860000,3.530000,...,10.370000,15.320000,13.51000,12.230000,14.680000,16.350000,18.140000,18.410000,17.310000,20.116142
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42367,F1472871E1AFF49D4289564B6377D76C,0,5.881217,5.660848,6.869079,6.935930,9.510250,5.397718,6.610850,7.269730,...,3.560000,3.380000,4.39000,3.720000,3.770000,3.960000,3.640000,3.400000,4.380000,9.510250
42368,F3C8BBCD2DC26C1E0249DEEF6A4256B7,0,2.700000,4.390000,3.950000,0.000000,0.000000,0.000000,0.000000,0.000000,...,4.870000,4.480000,3.67000,3.310000,4.580000,3.330000,3.190000,4.570000,4.000000,8.315122
42369,A9A0FE83467A680FBFB0DBFC910DF227,0,0.580000,0.840000,1.610000,0.900000,0.600000,0.820000,0.890000,0.030000,...,0.660000,2.920000,2.36000,3.860000,4.280000,3.370000,5.119539,2.440000,1.150000,5.119539
42370,D9A6ADA018FA46A55D5438370456AA45,0,16.890000,13.840000,13.500000,14.600000,14.460000,12.340000,15.370000,17.010000,...,13.750000,22.610000,18.83000,25.520000,18.110000,19.310000,17.480000,17.200000,15.280000,30.133722
42371,F3406636BAD1E6E0826E8EDDC9A1BF00,0,7.466225,7.355866,4.167959,5.493045,1.563728,6.813057,8.940603,7.702286,...,4.450000,9.800000,5.11000,15.214792,12.040000,9.900000,8.230000,8.560000,9.860000,15.214792

In [10]:
df_RL_ = Extraccion_caracteristicas(df_Linear_Regression, '0', '1033')

In [11]:
%%time
df_RL_.Sum()
df_RL_.Mean()
df_RL_.Median()
df_RL_.Standard_Dev()
df_RL_.Variance()
df_RL_.Peak_to_Peak()
df_RL_.Kurtosis()
df_RL_.Quartile_1()
df_RL_.Quartile_3()
df_RL_.Norm()
df_RL_.IQR()
df_RL_.Percentile_15()
df_RL_.Percentile_65()
df_RL_.Percentile_85()
df_RL_.Median_Absolute_Deviation()
df_RL_.kstat()
df_RL_.KStatvar()

Wall time: 30.9 s

In [12]:
df_Linear_Regression.fillna(0, inplace= True)
df_Linear_Regression.sample(5)

,CONS_NO,FLAG,0,1,2,3,4,5,6,7,...,Quartile_1,Quartile_3,Norm,IQR,Percentile_15,Percentile_65,Percentile_85,Median_Absolute_Deviation,kstat,KStatvar
31953,FE331D9A85D00232FB4F538565A88DC2,0,6.737936,6.111150,7.462795,7.206155,13.068552,6.811798,5.809448,7.339042,...,6.718999,8.477196,255.903539,1.758197,6.2900,7.920770,9.754866,0.800463,3.186598,0.032729
30077,390E96C377DE78E9D5A20F3C4A13925A,0,7.083127,6.758625,7.212141,7.282407,12.604005,6.362033,6.295923,6.975561,...,3.975347,7.698256,214.012276,3.722909,3.2495,7.077151,8.534136,1.667796,6.097823,0.059882
37714,D71ACC9BBBCF49931C2F38ACC279C12B,0,0.000000,4.520000,3.320000,5.490000,1.370000,5.660000,4.560000,5.890000,...,1.760000,3.677500,101.648705,1.917500,1.3295,3.170000,4.530000,0.930000,2.491310,0.010358
27683,6D1F24BC746C0C1BB83F46B7D3A2AD94,0,7.786515,5.427638,6.710680,7.271518,14.515524,6.350555,6.196172,7.267852,...,5.470000,8.167664,234.888064,2.697664,4.3800,7.590561,8.997086,1.277729,5.613255,0.080497
32856,15C057E7513B1BF4584CB5E72C2AEF37,0,7.344848,6.389783,7.219864,7.269959,12.537232,6.335094,6.341615,6.590498,...,4.298292,7.751780,218.546840,3.453488,3.6990,7.196424,8.506282,1.584416,5.088776,0.043388

In [13]:
df_Linear_Regression_grafico = Graficos(df_Linear_Regression)

In [14]:
interact_manual(
    df_Interpolation_Method_grafico.BoxPlot
    , Caracteristica = df_Linear_Regression.loc[:, 'Sum':]
    , limite = ['Ninguno', 'FLAG = 0', 'FLAG = 1', 'General']
)

interactive(children=(Dropdown(description='Caracteristica', options=('Sum', 'Mean', 'Median', 'Standard_Dev',…

---
### 2.2. División de train - test y Balanceo de datos

#### Interpolation Method

---
* Train - Test

In [15]:
df_Interpolation_Method

,CONS_NO,FLAG,2014/1/1,2014/1/10,2014/1/11,2014/1/12,2014/1/13,2014/1/14,2014/1/15,2014/1/16,...,Quartile_1,Quartile_3,Norm,IQR,Percentile_15,Percentile_65,Percentile_85,Median_Absolute_Deviation,kstat,KStatvar
0,0387DD8A07E07FDA6271170F86AD9151,1,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0000,11.7025,372.627771,11.7025,0.0000,8.3000,19.1455,6.310,75.497035,9.540462
1,01D6177B5D4FFE0CABA9EF17DAFC2B84,1,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0000,0.0000,0.000000,0.0000,0.0000,0.0000,0.0000,0.000,0.000000,0.000000
2,4B75AC4F2D8434CFF62DB64D0BB43103,1,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0000,0.0000,156.856654,0.0000,0.0000,0.0000,8.4020,0.000,18.949136,1.053040
3,B32AC8CC6D5D805AC053557AB05F5343,1,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0000,12.0400,366.470797,12.0400,0.0000,3.2145,19.2410,0.000,89.842842,15.908271
4,EDFC78B07BA2908B3395C4EB2304665E,1,2.90,3.42,3.81,4.58,3.56,4.25,3.86,3.53,...,4.6500,9.8600,290.229162,5.2100,4.0790,7.9045,12.2805,2.030,20.248953,1.230226
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42367,F1472871E1AFF49D4289564B6377D76C,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,1.0500,4.8400,125.481818,3.7900,0.0000,4.3900,5.4100,1.460,4.727048,0.020103
42368,F3C8BBCD2DC26C1E0249DEEF6A4256B7,0,2.70,4.39,3.95,0.00,0.00,0.00,0.00,0.00,...,3.8700,5.7675,159.656176,1.8975,3.3295,5.3300,6.3500,0.965,3.228289,0.031476
42369,A9A0FE83467A680FBFB0DBFC910DF227,0,0.58,0.84,1.61,0.90,0.60,0.82,0.89,0.03,...,0.4400,1.2600,56.287160,0.8200,0.2300,1.0000,1.9305,0.395,1.690566,0.014438
42370,D9A6ADA018FA46A55D5438370456AA45,0,16.89,13.84,13.50,14.60,14.46,12.34,15.37,17.01,...,11.5725,19.2250,544.075903,7.6525,8.6690,17.0590,22.3810,3.755,63.199415,8.075392
42371,F3406636BAD1E6E0826E8EDDC9A1BF00,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0000,4.7775,154.294361,4.7775,0.0000,0.0000,8.0605,0.000,17.027853,0.646760

In [25]:
'''
la división del los datos será de un 70 - 30
'''
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df_Interpolation_Method.drop(columns=['FLAG']) #Representando las X
                                                    , df_Interpolation_Method['FLAG'] #Representando la variable y
                                                    , test_size=0.3
                                                    , random_state= semilla
                                                    , stratify=df_Interpolation_Method['FLAG']
                                                   )

In [26]:
y_train.value_counts()

0    27130
1     2530
Name: FLAG, dtype: int64

In [24]:
y_test.value_counts()

0    11573
1     1139
Name: FLAG, dtype: int64

In [19]:
%%time
pd.concat([y_test ,X_test], axis=1).to_csv('{}Interpolation_Method_Test.csv'.format(ruta_df), index=False)

Wall time: 9.76 s

---
* Balanceo de datos

In [20]:
from imblearn.over_sampling import ADASYN 
ada = ADASYN(random_state= semilla
             , n_neighbors= 20
             , sampling_strategy=.8
             )

In [21]:
X, y = ada.fit_resample(X_train.drop(columns=['CONS_NO']), y_train)

In [22]:
%%time
pd.concat([y, X], axis=1).to_csv('{}Interpolation_Method_ADASYN_Train.csv'.format(ruta_df), index=False)

Wall time: 1min

In [23]:
from imblearn.over_sampling import SMOTE 
smote = SMOTE(random_state= semilla
             , sampling_strategy=.8
             )

In [24]:
X, y = smote.fit_resample(X_train.drop(columns=['CONS_NO']), y_train)

In [25]:
%%time
pd.concat([y, X], axis=1).to_csv('{}Interpolation_Method_SMOTE_Train.csv'.format(ruta_df), index=False)

Wall time: 1min 2s

---
#### Linear Regression

* Train - Test

In [26]:
'''
la división del los datos será de un 70 - 30
'''
X_train, X_test, y_train, y_test = train_test_split(df_Linear_Regression.drop(columns=['FLAG']) #Representando las X
                                                    , df_Linear_Regression['FLAG'] #Representando la variable y
                                                    , test_size=0.3
                                                    , random_state= semilla
                                                    , stratify=df_Interpolation_Method['FLAG']
                                                   )

In [27]:
%%time
pd.concat([y_test ,X_test], axis=1).to_csv('{}Linear_Regression_Test.csv'.format(ruta_df), index=False)

Wall time: 14 s

* Balanceo de datos

In [28]:
from imblearn.over_sampling import ADASYN 
ada = ADASYN(random_state= semilla
             , n_neighbors= 25
             , sampling_strategy=.8
             )

In [29]:
X, y = ada.fit_resample(X_train.drop(columns=['CONS_NO']), y_train)

In [30]:
%%time
pd.concat([y ,X], axis=1).to_csv('{}Linear_Regression_ADASYN_Train.csv'.format(ruta_df), index=False)

Wall time: 1min 14s

In [31]:
from imblearn.over_sampling import SMOTE 
smote = SMOTE(random_state= semilla
             , sampling_strategy=.8
             )

In [32]:
X, y = smote.fit_resample(X_train.drop(columns=['CONS_NO']), y_train)

In [33]:
%%time
pd.concat([y ,X], axis=1).to_csv('{}Linear_Regression_SMOTE_Train.csv'.format(ruta_df), index=False)

Wall time: 1min 13s