## 1. Datos Maestros de Productos

In [11]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

In [12]:
productos = pd.read_csv("productos.csv")

In [13]:
productos.sample(5)

,sku,categoria,subcategoria,talla,color,costo_unitario,precio_venta,proveedor_id,lead_time_dias,cantidad_minima_pedido,multiplico_pedido,temporada,margen
71,HM000072,Pantalones,Temporada,L,Azul,26.81,65.24,PROV072,8,50,50,Primavera,38.43
78,HM000079,Abrigos,Temporada,S,Azul,37.58,62.52,PROV079,16,200,10,Invierno,24.94
89,HM000090,Vestidos,Temporada,XL,Rojo,36.08,77.71,PROV090,14,500,50,Verano,41.63
36,HM000037,Camisetas,Premium,XS,Blanco,5.38,58.90,PROV037,20,200,50,Todo el año,53.52
48,HM000049,Vestidos,Temporada,XS,Negro,31.69,72.45,PROV049,17,500,50,Verano,40.76

## 2. Datos Históricos de Ventas (365 días)

In [14]:
ventas = pd.read_csv('ventas.csv')

In [15]:
ventas.sample(5)

,fecha,tienda,sku,cantidad_vendida,precio_venta_unitario,descuento_aplicado,venta_neta
442947,2023-06-22,TIENDA007,HM000069,1,30.26,0.0,30.260
503084,2023-07-15,TIENDA008,HM000045,1,90.97,0.0,90.970
917620,2023-12-23,TIENDA008,HM000040,1,59.59,0.0,59.590
45992,2023-01-18,TIENDA009,HM000064,2,91.93,0.1,165.474
924888,2023-12-26,TIENDA003,HM000024,3,98.10,0.2,235.440

## 3. Datos de Inventario Actual

In [16]:
inventario = pd.read_csv('inventario.csv')

In [17]:
inventario.sample(5)

,tienda,sku,stock_actual,stock_seguridad_actual,stock_en_transito,fecha_ultima_reposicion
519,TIENDA006,HM000032,19,16,8,2023-12-28
295,TIENDA003,HM000061,24,24,34,2024-01-14
592,TIENDA006,HM000087,3,27,12,2024-01-03
10,TIENDA001,HM000019,81,18,31,2024-01-05
418,TIENDA005,HM000013,5,24,28,2024-01-14

## 4. Datos de Escenarios con Costos Logísticos

In [20]:
Costos_Logisticos = pd.read_csv('Costos_Logisticos.csv')

In [21]:
Costos_Logisticos

,Escenario,costo_pedido,costo_mantenimiento_anual,costo_almacenamiento_m2,costo_transferencia_tienda,costo_rotura_stock,costo_obsolescencia
0,Escenario 1,10.0,0.15,80.0,3.0,0.20,0.09
1,Escenario 2,40.0,0.20,100.0,4.0,0.25,0.12
2,Escenario 3,50.0,0.25,120.0,5.0,0.30,0.15
3,Escenario 4,55.0,0.30,130.0,6.0,0.35,0.18
4,Escenario 5,60.0,0.35,140.0,7.0,0.38,0.20

## Modelos Prescriptivos

## 1: Sistema de Revisión Continua (s, Q) Optimizado

### Sistema de revisión continua de inventarios: Definición, métodos y ejemplos
https://www.ingenioempresa.com/sistema-de-revision-continua/#:~:text=de%20revisi%C3%B3n%20continua-,%C2%BFQu%C3%A9%20es%20un%20sistema%20de%20revisi%C3%B3n%20continua%20de%20inventarios?,debajo%20del%20nivel%2C%20sigue%20consumi%C3%A9ndose.

## 2: Proponer 3 modelos prescriptivos adicionales, tomando en consideración los datos de los escenarios de  Costos_Logisticos

   - **Optimización Multi-Periodo con Programación Lineal**
   - **Sistema de Transferencias entre Tiendas**
   - **Si es necesario emplear modelo como forecasting, regresiones**

## 3: Proponer Dashboard de Control Prescriptivo